import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Navbar from './components/Navbar/Navbar'


const date=new Date()
const y=date.getFullYear()
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vishal's BlogSpot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Bs.ico" />
      </Head>
        <Navbar/>
        
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Unique Blog
        </h1>
        <div className={styles.imagewrapper}>
        {/* <Image className={styles.imghome} src="https://c4.wallpaperflare.com/wallpaper/645/96/47/python-programming-programming-programming-language-code-hd-wallpaper-preview.jpg" */}
        <img src='https://c4.wallpaperflare.com/wallpaper/645/96/47/python-programming-programming-programming-language-code-hd-wallpaper-preview.jpg'
        width={100} height={100} className={styles.imghome}
        />
        </div>
        <p className={styles.description}>
          A unique Blog where Tech Solutions are provided on Whatsapp... 
        </p>
        <h2>Popular Blogs</h2>
        <div className={styles.grid}>
          <Link href="http://localhost:3000/blog"><a  className={styles.card}>
            <h3>A Complete Guide to Front-End Developer &rarr;</h3>
            <p>Find in-depth information about Front-End Developement and path.</p>
          </a>
          </Link>
          <Link href="http://localhost:3000/blog"><a className={styles.card}>
            <h3>A Complete Guide To Backend Developement &rarr;</h3>
            <p>Learn about Backend Developement and How you can become.... </p>
          </a></Link>

          <Link href="http://localhost:3000/blog"><a
           
            className={styles.card}
          >
            <h3>Top 5 javascript Errors &rarr;</h3>
            <p>Discover and solve Commom errors you will tackle in Js.</p>
          </a></Link>

          <Link href="http://localhost:3000/blog"><a
           
            className={styles.card}
          >
            <h3>Basics of React &rarr;</h3>
            <p>
              Instantly create your first React App using React
            </p>
          </a></Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"

          target="_blank"
          rel="noopener noreferrer"
        >
          <span >
            <small>&copy; {y}</small>
          </span>
        </a>
      </footer>
    </div>
  )
}
